### ISSUE TITLE
Change `/api/item/reserve/:id` to return owner's contact info

### ISSUE THREAD

**Issue by Bentheburrito** [LumosCapstone/backend#21]
Currently, we return a success message when reserving an item is successful. However, the reserver needs to follow through with the owner to actually make use of their resource. The endpoint should instead return the owner's name and contact info.

We'll also need a new endpoint (`/api/item/confirm-reservation/:id`?) that confirms the reserve is now using the resource.

I think we'll also need an endpoint that allows the owner to cancel the reservation and re-list the resource if the reserver does not contact them, or changes their mind.

**Question**
Do we think the owner should be the one to confirm the reservation? I think in rideshare services, the driver is the one who confirms they've picked up someone, so maybe that's analogous to our situation as well?

**Comment by diegovega49** [comment]
I agree that the owner should have the final say since it's their property they're lending out.

>I think we'll also need an endpoint that allows the owner to cancel the reservation and re-list the resource if the reserver does not contact them, or changes their mind.

Reservers will also have this functionality correct?
