### ISSUE TITLE
Refactor `index.js`

### ISSUE THREAD

**Issue by Bentheburrito** [LumosCapstone/backend#31]
`index.js` is starting to get pretty big (350 lines as of writing), so it might be worth doing a refactor pass (preferably after the outstanding PRs that edit this file are merged).

suggestion: create individual `.js` files in the `/api/` directory for each endpoint body.

**Comment by diegovega49** [comment]
I will hold off [#16](https://github.com/LumosCapstone/backend/issues/16) until this is completed.
