### ISSUE TITLE
Create endpoint for fetching basic user data

### ISSUE THREAD

**Issue by udromero** [LumosCapstone/backend#32]
Need to able to make an API get request that retrieves the following user information from our database. This will be the basic data I'll need to verify login credentials entered on the front end with what we have in our data base. I'd like to be able to find a user's info based on a unique user name if possible.

The relative url path for the request may be something along the lines of: /api/user/:username

I would at least need the following data returned in the form of JSON object: 

{
    user_id: 1 (user tables primary key)
    username: "like" (if possible require it to be unique attribute in user table)
    email: "abc@gmail.com"
    password: "123"
}

**Comment by Bentheburrito** [comment]
I don't think we have usernames, just the user's full name (e.g. "John Smith")

Also, we would be returning the password_hash, not the password itself

**Comment by Bentheburrito** [comment]
> Also, we would be returning the password_hash, not the password itself

Actually, I don't think we should/need to do anything with the password outside of logging in, right?

**Comment by Bentheburrito** [comment]
@udromero when you get a chance, please leave a review on #37 to let us know if your needs outlined here are met (particularly using a user's ID instead of a username)
