### ISSUE TITLE
[Bug] `/api/item` should filter out reserved resources

### ISSUE THREAD

**Issue by Bentheburrito** [LumosCapstone/backend#34]
I found that `/api/item` returns all resources, no matter whether they're currently reserved/borrowed/unlisted - the only resources excluded are those that exceed the `max_distance` param.

**Comment by diegovega49** [comment]
I've looked at issue, it seems we can add another condition to the `WHERE` clause so we filter by the correct item status. Something like `WHERE reservation_status = ${ITEM.LISTED} and..` . I'll do more testing.
